#!/bin/bash 

sort -u terms.txt -o terms.txt  | perl break.pl < terms.txt > terms_formatted.txt | db_load -T -c duplicates=1 -f terms_formatted.txt -t btree te.idx &
sort -u emails.txt -o emails.txt | perl break.pl < emails.txt > emails_formatted.txt | db_load -T -c duplicates=1 -f emails_formatted.txt -t btree em.idx &
sort -u dates.txt -o dates.txt | perl break.pl < dates.txt > dates_formatted.txt | db_load -T -c duplicates=1 -f dates_formatted.txt -t btree da.idx &
sort -nu recs.txt -o recs.txt  | perl break.pl < recs.txt > recs_formatted.txt | db_load -T -c duplicates=1 -f recs_formatted.txt -t hash re.idx &
wait
